### ISSUE TITLE
Ping scanning Only?

### ISSUE THREAD

**Issue by idealeer** [sfan5/fi6s#2]
Hello! Can we just get the 'ping scanning' without providing the 'port'?

**Comment by sfan5** [comment]
You can run an ICMP scan just fine without the `-p` option.
![screenshot](https://user-images.githubusercontent.com/1042418/56801338-8074f680-681d-11e9-81b3-4c2b029cefa5.png)

**Comment by idealeer** [comment]
Thank you very much!!!
