### ISSUE TITLE
can't install fi6s on centos 7

### ISSUE THREAD

**Issue by LickosA** [sfan5/fi6s#4]
Hello!
I can't install fi6s on centos 7. Do you know how i can fix the error bellow:
```bash
[root@~ fi6s]# make BUILD_TYPE=release 
cc -pipe -std=c11 -pthread -fno-strict-aliasing -Wall -Wextra -Wno-sign-compare -Wcast-align -O3 -ggdb -DNDEBUG -c src/main.c -o obj/main.o
cc -pipe -std=c11 -pthread -fno-strict-aliasing -Wall -Wextra -Wno-sign-compare -Wcast-align -O3 -ggdb -DNDEBUG -c src/util.c -o obj/util.o
cc -pipe -std=c11 -pthread -fno-strict-aliasing -Wall -Wextra -Wno-sign-compare -Wcast-align -O3 -ggdb -DNDEBUG -c src/scan.c -o obj/scan.o
In file included from src/scan.c:8:0:
src/scan.c:46:5: error: missing binary operator before token "("
 #if ATOMIC_INT_LOCK_FREE != 2
     ^
src/scan.c: In function ‘scan_main’:
src/scan.c:134:3: warning: implicit declaration of function ‘usleep’ [-Wimplicit-function-declaration]
   usleep(STATS_INTERVAL * 1000);
   ^
make: *** [obj/scan.o] Erreur 1
```

**Comment by sfan5** [comment]
I don't know why this would break, but you can work around it by commenting (or removing) these lines:
https://github.com/sfan5/fi6s/blob/6f9c301ead1c91cb3ba5a2f9484a45b77db82a94/src/scan.c#L46-L48

**Comment by LickosA** [comment]
Unfortunately, it didn't work. It generated others that I don't understand. 

Is it possible for us to install your with docker? This may limit some errors.

**Comment by sfan5** [comment]
Yes, there is a Dockerfile you can use. Be aware that you need to use `--net=host` for scanning to work correctly.

**Comment by LickosA** [comment]
i tried to use dockerfile. But, you mention that i need to use `--net=host` for scanning to work correctly. Unfortunately, i got an errror 
```bash
[root@centos7-core-32gb fi6s]# docker run fi6s:Dockerfile -p 80 --net=2001:4212::/31
fi6s: unrecognized option: net=2001:4212::/31
```
When i remove this option, i got a warning that i don't have ipv6 connectivity.
```bash
[root@centos7-core-32gb fi6s]# docker run fi6s:Dockerfile -p 80 2001:4212::/31
Using default interface 'eth0'
Warning: Your machine does not seem to have any IPv6 connectivity
Option --router-mac is required but was not given.
[root@centos7-core-32gb fi6s]# 
```
I have an ipv6 connectivity on my host. any help???
